const SERVER_ISSUE = 500;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const DB_DUPLICATION_ERR = 409;
const SUCCESS = 200;
const CREATED = 201;

module.exports = {
  SERVER_ISSUE,
  UNAUTHORIZED,
  BAD_REQUEST,
  NOT_FOUND,
  DB_DUPLICATION_ERR,
  SUCCESS,
  CREATED,
  FORBIDDEN
};

