const SERVER_ISSUE = 500;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const SUCCESS = 200;
const CREATED = 201;
const NO_CONTENT = 204;

module.exports = { SERVER_ISSUE, BAD_REQUEST, NOT_FOUND, SUCCESS, CREATED, NO_CONTENT }; 


